#!/bin/bash
# run the AGR datafeed

# default output file names
DAFoutput=MGI_0.3_diseaseAnnotations.json
BGIoutput=MGI_0.3_basicGeneInformation.json

function Usage() {
    cat - <<ENDTEXT

$0 [-f feed] [-d DAFoutput] [-b BGIoutput] [MGI IDs ...]

    Run the AGR data feed generation:
	DAF (disease annotation file) and/or bgi (Basic Gene Info)

    -f daf|bgi		run only one of these feeds (default is both)
    -d DAFoutput	output file for DAF generation (default = $DAFoutput)
    -b BGFoutput	output file for BGF generation (default = $BGIoutput)
    MGI IDs	 passed to the data feed scripts to limit output

ENDTEXT
    exit 5
}
if [ "$1" == --help ]; then
    Usage
fi

# PYTHON path - just . and ./lib - hopefully this works
dir="$(dirname $0)"
PYTHONPATH="${dir}:${dir}/lib"
export PYTHONPATH

# defaults
runDAF=T
runBGI=T

args=$(getopt f:d:j: $*)
if [ $? != 0 ]; then
    Usage
fi
set -- $args

for i; do
    case "$i" in
    -f) case "$2" in
	daf) runBGI=F;;
	bgi) runDAF=F;;
	*)   Usage;;
	esac
	shift; shift;
	;;
    -d) DAFoutput="$2"; shift; shift
	;;
    -b) BGIoutput="$2"; shift; shift
	;;
    --) shift; break;;
    esac
done
#echo "runDAF $runDAF; runBGI $runBGI; DAFoutput $DAFoutput; BGIoutput $BGIoutput"

if [ $runBGI == T ]; then
    ./basicGeneInfo.py $* > $BGIoutput
fi
if [ $runDAF == T ]; then
    ./diseaseAnnotations.py $* > $DAFoutput
fi
